os: osx
install:
  - wget https://github.com/yonaskolb/XcodeGen/releases/download/2.10.1/xcodegen.zip
  - unzip xcodegen.zip
  - git clone https://github.com/PrivateFrameworks/ProtocolBuffer.git
  - cd ProtocolBuffer && ../xcodegen/bin/xcodegen && cd ..
  - xcodegen/bin/xcodegen
language: objective-c
xcode_project: PrivateProtocolBuffer.xcodeproj
# env:
  # - XCODE_SCHEME="Linked tests ios" DESTINATION="platform=iOS Simulator,name=iPhone 8"
  # - XCODE_SCHEME="Unlinked tests ios" DESTINATION="platform=iOS Simulator,name=iPhone 8"
  # - XCODE_SCHEME="Linked tests tvos" DESTINATION="platform=tvOS Simulator,name=Apple TV"
  # - XCODE_SCHEME="Unlinked tests tvos" DESTINATION="platform=tvOS Simulator,name=Apple TV"
  # - XCODE_SCHEME="Linked tests macos" DESTINATION="platform=macOS"
  # - XCODE_SCHEME="Unlinked tests macos" DESTINATION="platform=macOS"
script:
  - bash -c "$BEFORE"
  - bash -c "xcodebuild test -project PrivateProtocolBuffer.xcodeproj -scheme $XCODE_SCHEME -destination $DESTINATION"

matrix:
  include:
    - env: XCODE_SCHEME="Linked\\ tests\\ ios" DESTINATION="platform=iOS\\ Simulator,name=iPhone\\ 8" BEFORE="xcrun simctl boot iPhone\\ 8 && sleep 5 && xcrun simctl openurl booted http://stream.radioreklama.bg/radio164 && sleep 5"
      osx_image: xcode10.2

    # - env: XCODE_SCHEME="Linked\\ tests\\ macos" DESTINATION="platform=macOS" BEFORE="open /System/Library/Sounds/*"
    #   osx_image: xcode10.2
