#ifndef PrivateMediaRemote_Constants_h
#define PrivateMediaRemote_Constants_h

extern NSString *kMRMediaRemoteNowPlayingInfoDidChangeNotification;
extern NSString *kMRMediaRemoteNowPlayingPlaybackQueueDidChangeNotification;
extern NSString *kMRMediaRemotePickableRoutesDidChangeNotification;
extern NSString *kMRMediaRemoteNowPlayingApplicationDidChangeNotification;
extern NSString *kMRMediaRemoteNowPlayingApplicationIsPlayingDidChangeNotification;
extern NSString *kMRMediaRemoteRouteStatusDidChangeNotification;
extern NSString *kMRNowPlayingPlaybackQueueChangedNotification;
extern NSString *kMRPlaybackQueueContentItemsChangedNotification;

extern NSString *kMRMediaRemoteNowPlayingInfoArtist;
extern NSString *kMRMediaRemoteNowPlayingInfoTitle;
extern NSString *kMRMediaRemoteNowPlayingInfoAlbum;
extern NSString *kMRMediaRemoteNowPlayingInfoArtworkData;
extern NSString *kMRMediaRemoteNowPlayingInfoPlaybackRate;
extern NSString *kMRMediaRemoteNowPlayingInfoDuration;
extern NSString *kMRMediaRemoteNowPlayingInfoElapsedTime;
extern NSString *kMRMediaRemoteNowPlayingInfoTimestamp;
extern NSString *kMRMediaRemoteNowPlayingInfoClientPropertiesData;

extern NSString *kMRActiveNowPlayingPlayerPathUserInfoKey;
extern NSString *kMRMediaRemoteNowPlayingApplicationDisplayNameUserInfoKey;
extern NSString *kMRMediaRemoteNowPlayingApplicationIsPlayingUserInfoKey;
extern NSString *kMRMediaRemoteNowPlayingApplicationIsPlayingUserInfoKey;
extern NSString *kMRMediaRemoteNowPlayingApplicationPIDUserInfoKey;
extern NSString *kMRMediaRemoteOriginUserInfoKey;
extern NSString *kMRMediaRemotePlaybackStateUserInfoKey;
extern NSString *kMRMediaRemoteUpdatedContentItemsUserInfoKey;
extern NSString *kMRNowPlayingClientUserInfoKey;
extern NSString *kMRNowPlayingPlayerPathUserInfoKey;
extern NSString *kMRNowPlayingPlayerUserInfoKey;
extern NSString *kMROriginActiveNowPlayingPlayerPathUserInfoKey;

#endif /* PrivateMediaRemote_Constants_h */
