name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Play sounds
        run: open /System/Library/Sounds/*

      - name: Run tests
        run: swift test -v
